### ISSUE TITLE
EDQM Bindings überprüfen

### ISSUE THREAD

**Issue by simoneOnFhir** [medizininformatik-initiative/kerndatensatzmodul-medikation#11]
Betrifft Dosage.site, .route, .method und Medication.form .

**Comment by julsas** [comment]
EDQM Bindings im KDS nach IPS Vorgaben:
* Dosage.site from http://hl7.org/fhir/uv/ips/ValueSet/target-site-uv-ips (IPS)
* Dosage.route from http://hl7.org/fhir/uv/ips/ValueSet/medicine-route-of-administration (IPS)
* Dosage.method nicht spezifiziert
* Medication.form from http://hl7.org/fhir/uv/ips/ValueSet/medicine-doseform (IPS)
