### ISSUE TITLE
Validation of MedicationStatement fails

### ISSUE THREAD

**Issue by ChristophB** [medizininformatik-initiative/kerndatensatzmodul-medikation#13]
MedicationStatement does not satisfy constraint sdf-10 ("provide either a binding reference or a description (or both)") for type StructureDefinition.

https://github.com/medizininformatik-initiative/kerndatensatzmodul-medikation/blob/4b6eb7bf32c48be901e6e494b2f14a8ebc3da913/ressourcen-profile/MedicationStatement.StructureDefinition.xml#L132-L138

Lines 135-137 should either be removed or a description should be added.

**Comment by ChristophB** [comment]
The same applies to MedicationAdministration.

https://github.com/medizininformatik-initiative/kerndatensatzmodul-medikation/blob/4b6eb7bf32c48be901e6e494b2f14a8ebc3da913/ressourcen-profile/MedicationAdministration.StructureDefinition.xml#L124-L130

**Comment by alexzautke** [comment]
@ChristophB Vielen Dank für den Hinweis, wir schauen uns das Problem schnellmöglich an.

**Comment by alexzautke** [comment]
Assigning to @julsas
