### ISSUE TITLE
CapabilityStatement und SearchParameter

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-medikation#22]
CapabilityStatement als Technical Correction für 1.x

CapabilityStatement und SearchParameter für 2.x hinzufügen

**Comment by alexzautke** [comment]
CapabilityStatement für 1.x sollte keine Suchparameter enthalten. Nur die Ressourcen.

**Comment by julsas** [comment]
1b61f7ad2d821f3a2dcb307d034f0f56b38a58fa
2c18a0f19044fdecfb13d46a5bc6c0dd775a8640
05067884dd671094bbdcda8846f996cbcec47d73
