### ISSUE TITLE
Comment HL7 Ballot No. 05: FHIR-Profil Medication "denominator"

### ISSUE THREAD

**Issue by beakmachine** [medizininformatik-initiative/kerndatensatzmodul-medikation#30]
https://tmfev.sharepoint.com/:w:/r/sites/tmf/mi-i/Taskforce%20Kerndatensatz/03_Basismodule/Modul_Medikation/02_Dokumente/%5B20230215_MII_Med_2.0_kommentare_Jira.docx%5D(https://tmfev.sharepoint.com/:w:/r/sites/tmf/mi-i/Taskforce%20Kerndatensatz/03_Basismodule/Modul_Medikation/02_Dokumente/20230215_MII_Med_2.0_kommentare_Jira.docx?d=w9b8640d303c94d07a1ff734c963d5e03&csf=1&web=1&e=KqLyWL)?d=w9b8640d303c94d07a1ff734c963d5e03&csf=1&web=1&e=KqLyWL

Bei der Packungsangabe ist ohne angabe der Unit im denominator nicht klar um was sich der code: 1 handelt. 
Bei unserem Austauschformat haben wir dies so gelöst: 
 "denominator" : {
      "value" : 1,
      "unit" : "Package",
      "system" : "http://unitsofmeasure.org",
      "code" : "{Package}"
    }
So ist es klarer, dass sich hier um eine Packung handelt.

Generated at Wed Feb 15 14:12:04 UTC 2023 by Julian Sass using Jira 1001.0.0-SNAPSHOT#100216-sha1:a1e76114553265baf434fc585292d830f0e4b4ae

@beakmachine , @julsas, @ganslats  : Soweit ich sehe, bezieht sich der Kommentar auf "amount". Ich denke, für Packungsangaben (wenn dies wirklich feststeht, dass es sich um eine Packung handelt) kann man das so machen.
Ich würde das aber nicht grundsätzlich so festlegen, weil es für Rezepturen (ohne PZN) sicherlich nicht stimmt. Man kann es aber in den Implementation-Guide schreiben.

**Comment by julsas** [comment]
Der Kommentar bezieht sich auf `.amount` in diesem Beispiel:  https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.medikation/2.0.0-ballot1/files/791308/~json

Die Abbildung ist nach Abstimmung mit der KBV entstanden ähnlich hier: https://simplifier.net/packages/kbv.basis/1.3.0/files/657710/~json

Ich würde "Package" in `unit` schreiben, aber nicht in `code` als UCUM Annotation. HL7 dazu: 
> Curly braces {} in the code element are discouraged. Curly braces provide additional descriptive text in the code expression but do not contribute to the meaning of the code.

https://terminology.hl7.org/UCUM.html#ucum-expressions

**Comment by beakmachine** [comment]
Siehe Kommentar von julsas.

@julsas : ist das richtig so?

Dieses Vorgehen in den IG aufgenommen:

"Package" als UCUM Annotation in unit.

 "amount": {
        "numerator": {
            "value": 27,
            "unit": "Tablet",
            "system": "http://standardterms.edqm.eu",
            "code": "10219000"
        },
        "denominator": {
            "value": 1,
            "unit": "Package",
            "system": "http://unitsofmeasure.org",
            "code": "1"
        }
    },
