### ISSUE TITLE
List.code.coding:medCode

### ISSUE THREAD

**Issue by alexzautke** [medizininformatik-initiative/kerndatensatzmodul-medikation#49]
[Natalia Strauch](https://simplifier.net/user/nataliastrauch) commented 6 months ago
Binding fehlt bzw. welcher Code wird hier erwartet?
 avatar
[Julian Sass](https://simplifier.net/user/juliansass) commented 6 months ago
Kein Binding notwendig. Ist nur ein Code und in dem Fall ein Pattern auf List.code.coding:medCode

**Comment by julsas** [comment]
Es wird der Code "medications" aus dem System http://terminology.hl7.org/CodeSystem/list-example-use-codes erwartet:

https://github.com/medizininformatik-initiative/kerndatensatzmodul-medikation/blob/9e711095e419f5b1e523c8d6cb255971999242cd/fsh-generated/resources/StructureDefinition-mii-pr-medikation-medikationsliste.json#L162-L171
